### ISSUE TITLE
Problem installing fixture

### ISSUE THREAD

**Issue by tiagovaz** [tiagovaz/saskatoon#117]
It seems the current database is inconsistent in some way, I can't load a full dump from July 5:

```
Loading 'dump' fixtures...
Checking '/home/tiago/Hacking/saskatoon/saskatoon' for fixtures...
Installing json fixture 'dump' from '/home/tiago/Hacking/saskatoon/saskatoon'.
Processed 1048 object(s).Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 148, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/core/serializers/base.py", line 201, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/tiago/Hacking/saskatoon/saskatoon/harvest/signals.py", line 26, in comment_send_mail
    if instance.author.email != instance.harvest.pick_leader.email:
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related_descriptors.py", line 169, in __get__
    rel_obj = qs.get()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
harvest.models.DoesNotExist: Problem installing fixture '/home/tiago/Hacking/saskatoon/saskatoon/dump.json': Harvest matching query does not exist.

```

**Comment by tassia** [comment]
hey noel, any take on this?
tiago says he has been copying the whole database...
could you test and check if the bug is still relevant?
